services:
  # MySQL服务（带数据持久化）
  mysql8:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # 初始化脚本目录（可选，首次启动时执行）
      # - ./script/mysql/:/docker-entrypoint-initdb.d/
      # MySQL数据持久化卷（核心：将数据目录映射到宿主机或命名卷）
      - mysql_data:/var/lib/mysql  # /var/lib/mysql是MySQL容器内默认数据目录
    ports:
      - "3306:3306"

  # Redis服务（带数据持久化）
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - REDIS_PASSWORD=redis  # 替换为你的密码
    volumes:
      # Redis数据持久化卷（核心：容器内数据目录映射到命名卷）
      - redis_data:/data  # /data是Redis容器内默认数据目录
    ports:
      - '6379:6379'

# 声明命名卷（用于存储MySQL和Redis的数据，独立于容器生命周期）
volumes:
  mysql_data:  # MySQL数据卷
  redis_data:  # Redis数据卷