mysql8:
  image: mysql:8.0.29
  restart: always
  command: bash
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
    # 设置初始化脚本
    ./script/mysql/:/docker-entrypbint-initdb.d/
  ports:
    # 注意这里我映射为了 13316 端口
    "5000:5000"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      '8000:8000'