apiVersion: v1
kind: Service
metadata:
  name: webook-service
spec:
  selector:
    app: webook
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30081
  type: LoadBalancer 